export const pageCopy =  [{
breakfastTitle: "Start your day like a local...",
breakfastDescription: "Settle into the embrace of our charming mountain town, where each hidden gem offers a taste of the past. Here, the allure of timeless culinary artistry and breathtaking landscapes meld seamlessly, inviting you to indulge in the tranquility and savor the flavors of breakfast spots unspoiled by time. From the sunlit elegance of Maison du Soleil to the vibrant zest of Bamboo Bistro, every moment is a step into a more serene, flavorful world. Welcome to a place where every bite is a journey, and every meal is a cherished memory in the making.",
breakfastPlaceA: "Maison du Soleil",
breakfastPlaceADollars: "$$$",
breakfastPlaceAAddress: "3419 Terra Vale St Terra Vale, MT 59001",
breakfastPlaceAWebsite: "www.mdusoleil.com",
breakfastPlaceAPhoneNumber: "482.912.7301",
breakfastPlaceADescription: "A culinary haven offering French-inspired breakfast delicacies, where every bite transports you to the sunlit streets of Paris.",
breakfastPlaceB: "Bamboo Bistro",
breakfastPlaceBDollars: "$$$$",
breakfastPlaceBAddress: "1219 Corner St Terra Vale, MT 59001",
breakfastPlaceBWebsite: "www.bamboobistro.com",
breakfastPlaceBPhoneNumber: "482.693.5844",
breakfastPlaceBDescription: "Experience the vibrant flavors of Asian cuisine in a breakfast spread, blending traditional recipes with a modern twist.",
dinnerTitle: "Dinner for All",
dinnerDescription: "As the sun sets, our mountain town reveals culinary gems like Saffron Grill and Aubergine Oasis, where flavors dance in harmonious blend. Here, each dish is a journey, a harmonious blend of tradition and innovation, inviting you to savor the tranquility and exquisite craftsmanship of our culinary sanctuaries. Welcome to a serene escape where every meal is a cherished moment in timeless gastronomy.",
dinnerPlaceA: "Saffron Grill",
dinnerPlaceADollars: "$$$$$",
dinnerPlaceAAddress: "3419 Terra Vale St Terra Vale, MT 59001",
dinnerPlaceAWebsite: "www.saffrongrill.com",
dinnerPlaceAPhoneNumber: "482.703.1301",
dinnerPlaceADescription: "Indulge in a rich array of exquisite Middle Eastern dinner dishes, each infused with the aromatic allure of spices and herbs, promising a culinary journey like no other.",
dinnerPlaceB: "Aubergine Oasis",
dinnerPlaceBDollars: "$$$$",
dinnerPlaceBAddress: "1219 Corner St Terra Vale, MT 59001",
dinnerPlaceBWebsite: "www.aoasis-tvmt.com",
dinnerPlaceBPhoneNumber: "482.908.1120",
dinnerPlaceBDescription: "Delight in a diverse menu of Mediterranean dinner creations, each dish a harmonious blend of bold flavors and fresh, high-quality ingredients.",

}]